# CS 2308 - Program 4
# makefile for TowerOfTerror class program with two files:
# Queue.h,
# TowerOfTerror.cpp

a.out: TowerOfTerror.o
	g++ -std=gnu++0x TowerOfTerror.o Queue.h

TowerOfTerror.o: TowerOfTerror.cpp Queue.h
	g++ -std=gnu++0x -c TowerOfTerror.cpp